# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'ZHChatSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'ZHChat', '~> 0.2.1'
  # Pods for ZHChatSwift

  target 'ZHChatSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZHChatSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
